function duty = Cascade_duty_Boost(IL,IL_eq_ref,Ki_v,Kp_i,Kp_v,L,R_L,VD,Vin,Vout,Vout_ref,int_eVout)
%Cascade_duty_Boost
%    DUTY = Cascade_duty_Boost(IL,IL_eq_ref,Ki_v,Kp_i,Kp_v,L,R_L,VD,Vin,Vout,Vout_ref,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Jul-2026 14:58:34

duty = -(Vin-IL.*R_L+Kp_i.*L.*(IL-IL_eq_ref+Kp_v.*(Vout-Vout_ref+Ki_v.*int_eVout)))./(VD+Vout)+1.0;
end
