function gains_expr = Cascade_gains_Buck(C,k,ts,zeta)
%Cascade_gains_Buck
%    GAINS_EXPR = Cascade_gains_Buck(C,K,TS,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Jul-2026 14:58:44

gains_expr = [8.0./(ts-k.*ts);(1.0./zeta.^2.*(C.*2.0-C.*k.*2.0+C.*k.*zeta.^2.*8.0))./(ts.*3.0);(k.*8.0)./(ts-k.*ts+k.*ts.*zeta.^2.*4.0)];
end
