function gains_expr = IDAPBC_gains_Boost(C,L,R_L,k,ts,zeta)
%IDAPBC_gains_Boost
%    GAINS_EXPR = IDAPBC_gains_Boost(C,L,R_L,K,TS,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Jul-2026 11:11:15

gains_expr = [(sqrt(C).*sqrt(L).*sqrt(((-k+k.*zeta.^2.*4.0+1.0).*(-6.4e+1./3.0))./(k-1.0)))./(ts.*zeta.*2.0);(L.*8.0)./(R_L.*ts-R_L.*k.*ts);(sqrt(C).*sqrt(L).*k.*1.0./ts.^2.*sqrt(((-k+k.*zeta.^2.*4.0+1.0).*(-6.4e+1./3.0))./(k-1.0)).*4.0)./(zeta.*(L-L.*k+L.*k.*zeta.^2.*4.0))];
end
