function d_dot = Krasovskii_duty_Buck(IL,IL_ref,IL_dot,K_u,Kp_i,Kp_v,VD,Vin,Vout,Vout_ref)
%Krasovskii_duty_Buck
%    D_DOT = Krasovskii_duty_Buck(IL,IL_ref,IL_dot,K_u,Kp_i,Kp_v,VD,Vin,Vout,Vout_ref)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Jul-2026 14:27:06

d_dot = -K_u.*(IL_dot.*VD+IL_dot.*Vin)-Kp_v.*(Vout-Vout_ref)-Kp_i.*(IL-IL_ref);
end
