function gains_expr = Krasovskii_gains_Buck(C,L,R_L,Vin,k,ts,zeta)
%Krasovskii_gains_Buck
%    GAINS_EXPR = Krasovskii_gains_Buck(C,L,R_L,Vin,K,TS,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Jul-2026 14:27:06

gains_expr = [(L.*8.0-R_L.*ts+R_L.*k.*ts)./(Vin.^2.*ts-Vin.^2.*k.*ts);(C.*L.*k.*1.28e+2)./(Vin.*ts.^3.*zeta.^2.*3.0-Vin.*k.*ts.^3.*zeta.^2.*3.0);(ts.^2.*zeta.^2.*-3.0+C.*L.*1.6e+1-C.*L.*k.*1.6e+1+k.*ts.^2.*zeta.^2.*3.0+C.*L.*k.*zeta.^2.*6.4e+1)./(C.*Vin.*ts.^2.*zeta.^2-C.*Vin.*k.*ts.^2.*zeta.^2)];
end
