function alpha_IL = alpha_modelFree_expr(L,VD,Vin,Vout,converter)
%alpha_modelFree_expr
%    alpha_IL = alpha_modelFree_expr(L,VD,Vin,Vout,CONVERTER)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    17-Apr-2026 12:22:23

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 2.0)
    alpha_IL = (VD+Vin-Vout)./L;
elseif (converter == 1.0)
    alpha_IL = (VD+Vin)./L;
elseif (converter == 0.0)
    alpha_IL = (VD+Vout)./L;
else
    alpha_IL = 0.0;
end
end
