function duty = Cascade_duty(IL,IL_eq_ref,Ki_v,Kp_i,Kp_v,L,R_L,VD,Vin,Vout,Vout_ref,converter,int_eVout)
%Cascade_duty
%    DUTY = Cascade_duty(IL,IL_eq_ref,Ki_v,Kp_i,Kp_v,L,R_L,VD,Vin,Vout,Vout_ref,CONVERTER,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Jul-2026 10:57:52

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    duty = (VD+Vout+IL.*R_L-Kp_i.*L.*(IL-IL_eq_ref+Kp_v.*(Vout-Vout_ref+Ki_v.*int_eVout)))./(VD+Vin);
elseif (converter == 0.0)
    duty = -(Vin-IL.*R_L+Kp_i.*L.*(IL-IL_eq_ref+Kp_v.*(Vout-Vout_ref+Ki_v.*int_eVout)))./(VD+Vout)+1.0;
else
    duty = 0.0;
end
end
