function duty = Cascade_duty_Buck(IL,IL_eq_ref,Ki_v,Kp_i,Kp_v,L,R_L,VD,Vin,Vout,Vout_ref,int_eVout)
%Cascade_duty_Buck
%    DUTY = Cascade_duty_Buck(IL,IL_eq_ref,Ki_v,Kp_i,Kp_v,L,R_L,VD,Vin,Vout,Vout_ref,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Jul-2026 17:15:49

duty = (VD+Vout+IL.*R_L-Kp_i.*L.*(IL-IL_eq_ref+Kp_v.*(Vout-Vout_ref+Ki_v.*int_eVout)))./(VD+Vin);
end
