function gains_expr = Cascade_gains(C,IL_eq_ref,L,VD,Vin,Vout_ref,converter,k,ts,zeta)
%Cascade_gains
%    GAINS_EXPR = Cascade_gains(C,IL_eq_ref,L,VD,Vin,Vout_ref,CONVERTER,K,TS,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Jul-2026 10:57:52

et1 = IL_eq_ref.^2.*Vin.^3.*ts.^3.*zeta.^2.*9.0+C.^2.*VD.^4.*Vin.*ts.*1.6e+1+C.^2.*Vin.*Vout_ref.^4.*ts.*1.6e+1+C.^2.*VD.^2.*Vin.*Vout_ref.^2.*ts.*9.6e+1+C.^2.*IL_eq_ref.*L.*VD.^4.*k.*1.28e+2+C.^2.*IL_eq_ref.*L.*Vout_ref.^4.*k.*1.28e+2-IL_eq_ref.^2.*Vin.^3.*k.*ts.^3.*zeta.^2.*9.0+C.^2.*VD.*Vin.*Vout_ref.^3.*ts.*6.4e+1+C.^2.*VD.^3.*Vin.*Vout_ref.*ts.*6.4e+1-C.^2.*VD.^4.*Vin.*k.*ts.*1.6e+1-C.^2.*Vin.*Vout_ref.^4.*k.*ts.*1.6e+1-C.*IL_eq_ref.*VD.^2.*Vin.^2.*ts.^2.*zeta.^2.*2.4e+1-C.*IL_eq_ref.*Vin.^2.*Vout_ref.^2.*ts.^2.*zeta.^2.*2.4e+1+C.^2.*IL_eq_ref.*L.*VD.*Vout_ref.^3.*k.*5.12e+2;
et2 = C.^2.*IL_eq_ref.*L.*VD.^3.*Vout_ref.*k.*5.12e+2-C.^2.*VD.*Vin.*Vout_ref.^3.*k.*ts.*6.4e+1-C.^2.*VD.^3.*Vin.*Vout_ref.*k.*ts.*6.4e+1+C.^2.*IL_eq_ref.*L.*VD.^2.*Vout_ref.^2.*k.*7.68e+2-C.^2.*VD.^2.*Vin.*Vout_ref.^2.*k.*ts.*9.6e+1+C.^2.*VD.^4.*Vin.*k.*ts.*zeta.^2.*6.4e+1+C.^2.*Vin.*Vout_ref.^4.*k.*ts.*zeta.^2.*6.4e+1+C.^2.*VD.*Vin.*Vout_ref.^3.*k.*ts.*zeta.^2.*2.56e+2+C.^2.*VD.^3.*Vin.*Vout_ref.*k.*ts.*zeta.^2.*2.56e+2+C.^2.*VD.^2.*Vin.*Vout_ref.^2.*k.*ts.*zeta.^2.*3.84e+2-C.*IL_eq_ref.*VD.*Vin.^2.*Vout_ref.*ts.^2.*zeta.^2.*4.8e+1;
et3 = IL_eq_ref.*Vin.^3.*ts.^3.*zeta.^2.*-3.0+C.*IL_eq_ref.^2.*L.^2.*VD.^2.*k.*1.28e+2+C.*IL_eq_ref.^2.*L.^2.*Vout_ref.^2.*k.*1.28e+2+IL_eq_ref.*Vin.^3.*k.*ts.^3.*zeta.^2.*3.0+C.*VD.^2.*Vin.^2.*ts.^2.*zeta.^2.*8.0+C.*Vin.^2.*Vout_ref.^2.*ts.^2.*zeta.^2.*8.0+C.*IL_eq_ref.^2.*L.^2.*VD.*Vout_ref.*k.*2.56e+2+C.*VD.*Vin.^2.*Vout_ref.*ts.^2.*zeta.^2.*1.6e+1+C.*IL_eq_ref.*L.*VD.^2.*Vin.*ts.*1.6e+1+C.*IL_eq_ref.*L.*Vin.*Vout_ref.^2.*ts.*1.6e+1-C.*IL_eq_ref.*L.*VD.^2.*Vin.*k.*ts.*1.6e+1-C.*IL_eq_ref.*L.*Vin.*Vout_ref.^2.*k.*ts.*1.6e+1+C.*IL_eq_ref.*L.*VD.*Vin.*Vout_ref.*ts.*3.2e+1-C.*IL_eq_ref.*L.*VD.*Vin.*Vout_ref.*k.*ts.*3.2e+1;
et4 = C.*IL_eq_ref.*L.*VD.^2.*Vin.*k.*ts.*zeta.^2.*6.4e+1+C.*IL_eq_ref.*L.*Vin.*Vout_ref.^2.*k.*ts.*zeta.^2.*6.4e+1+C.*IL_eq_ref.*L.*VD.*Vin.*Vout_ref.*k.*ts.*zeta.^2.*1.28e+2;
et5 = IL_eq_ref.^2.*Vin.^3.*ts.^3.*zeta.^2.*9.0+C.^2.*VD.^4.*Vin.*ts.*1.6e+1+C.^2.*Vin.*Vout_ref.^4.*ts.*1.6e+1+C.^2.*VD.^2.*Vin.*Vout_ref.^2.*ts.*9.6e+1+C.^2.*IL_eq_ref.*L.*VD.^4.*k.*1.28e+2+C.^2.*IL_eq_ref.*L.*Vout_ref.^4.*k.*1.28e+2-IL_eq_ref.^2.*Vin.^3.*k.*ts.^3.*zeta.^2.*9.0+C.^2.*VD.*Vin.*Vout_ref.^3.*ts.*6.4e+1+C.^2.*VD.^3.*Vin.*Vout_ref.*ts.*6.4e+1-C.^2.*VD.^4.*Vin.*k.*ts.*1.6e+1-C.^2.*Vin.*Vout_ref.^4.*k.*ts.*1.6e+1-C.*IL_eq_ref.*VD.^2.*Vin.^2.*ts.^2.*zeta.^2.*2.4e+1-C.*IL_eq_ref.*Vin.^2.*Vout_ref.^2.*ts.^2.*zeta.^2.*2.4e+1+C.^2.*IL_eq_ref.*L.*VD.*Vout_ref.^3.*k.*5.12e+2;
et6 = C.^2.*IL_eq_ref.*L.*VD.^3.*Vout_ref.*k.*5.12e+2-C.^2.*VD.*Vin.*Vout_ref.^3.*k.*ts.*6.4e+1-C.^2.*VD.^3.*Vin.*Vout_ref.*k.*ts.*6.4e+1+C.^2.*IL_eq_ref.*L.*VD.^2.*Vout_ref.^2.*k.*7.68e+2-C.^2.*VD.^2.*Vin.*Vout_ref.^2.*k.*ts.*9.6e+1+C.^2.*VD.^4.*Vin.*k.*ts.*zeta.^2.*6.4e+1+C.^2.*Vin.*Vout_ref.^4.*k.*ts.*zeta.^2.*6.4e+1+C.^2.*VD.*Vin.*Vout_ref.^3.*k.*ts.*zeta.^2.*2.56e+2+C.^2.*VD.^3.*Vin.*Vout_ref.*k.*ts.*zeta.^2.*2.56e+2+C.^2.*VD.^2.*Vin.*Vout_ref.^2.*k.*ts.*zeta.^2.*3.84e+2-C.*IL_eq_ref.*VD.*Vin.^2.*Vout_ref.*ts.^2.*zeta.^2.*4.8e+1;
et7 = IL_eq_ref.*Vin.^3.*ts.^3.*zeta.^2.*-3.0+C.*IL_eq_ref.^2.*L.^2.*VD.^2.*k.*1.28e+2+C.*IL_eq_ref.^2.*L.^2.*Vout_ref.^2.*k.*1.28e+2+IL_eq_ref.*Vin.^3.*k.*ts.^3.*zeta.^2.*3.0+C.*VD.^2.*Vin.^2.*ts.^2.*zeta.^2.*8.0+C.*Vin.^2.*Vout_ref.^2.*ts.^2.*zeta.^2.*8.0+C.*IL_eq_ref.^2.*L.^2.*VD.*Vout_ref.*k.*2.56e+2+C.*VD.*Vin.^2.*Vout_ref.*ts.^2.*zeta.^2.*1.6e+1+C.*IL_eq_ref.*L.*VD.^2.*Vin.*ts.*1.6e+1+C.*IL_eq_ref.*L.*Vin.*Vout_ref.^2.*ts.*1.6e+1-C.*IL_eq_ref.*L.*VD.^2.*Vin.*k.*ts.*1.6e+1-C.*IL_eq_ref.*L.*Vin.*Vout_ref.^2.*k.*ts.*1.6e+1+C.*IL_eq_ref.*L.*VD.*Vin.*Vout_ref.*ts.*3.2e+1-C.*IL_eq_ref.*L.*VD.*Vin.*Vout_ref.*k.*ts.*3.2e+1;
et8 = C.*IL_eq_ref.*L.*VD.^2.*Vin.*k.*ts.*zeta.^2.*6.4e+1+C.*IL_eq_ref.*L.*Vin.*Vout_ref.^2.*k.*ts.*zeta.^2.*6.4e+1+C.*IL_eq_ref.*L.*VD.*Vin.*Vout_ref.*k.*ts.*zeta.^2.*1.28e+2;
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t0 = 8.0./(ts-k.*ts);
elseif (converter == 0.0)
    t0 = -(1.0./Vin.^2.*1.0./ts.^3.*1.0./zeta.^2.*(et7+et8))./((k-1.0).*(IL_eq_ref.^2.*L.*3.0+C.*VD.^2+C.*Vout_ref.^2+C.*VD.*Vout_ref.*2.0));
else
    t0 = 0.0;
end
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t1 = (1.0./zeta.^2.*(C.*2.0-C.*k.*2.0+C.*k.*zeta.^2.*8.0))./(ts.*3.0);
elseif (converter == 0.0)
    t1 = (et5+et6)./((VD+Vout_ref).*(et3+et4).*3.0);
else
    t1 = 0.0;
end
mt1 = [t0;t1];
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t0 = (k.*8.0)./(ts-k.*ts+k.*ts.*zeta.^2.*4.0);
elseif (converter == 0.0)
    t0 = (Vin.*(VD+Vout_ref).*(C.*VD.*k+C.*Vout_ref.*k).*(IL_eq_ref.^2.*L.*3.0+C.*VD.^2+C.*Vout_ref.^2+C.*VD.*Vout_ref.*2.0).*1.28e+2)./(et1+et2);
else
    t0 = 0.0;
end
mt2 = [t0];
gains_expr = [mt1;mt2];
end
