function d_dot = d_dot_expr(IL,IL_dot,K_u,Vin,Vout,Vout_dot,converter)
%D_DOT_EXPR
%    D_DOT = D_DOT_EXPR(IL,IL_dot,K_u,Vin,Vout,Vout_dot,CONVERTER)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Apr-2026 19:06:35

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 2.0)
    d_dot = -K_u.*(IL_dot.*(Vin-Vout)-IL.*Vout_dot);
elseif (converter == 1.0)
    d_dot = -IL_dot.*K_u.*Vin;
elseif (converter == 0.0)
    d_dot = K_u.*(IL.*Vout_dot-IL_dot.*Vout);
else
    d_dot = 0.0;
end
end
