function d_ref = d_ref_expr(I_load,R_L,VD,Vin,Vout,converter,n_phases)
%D_REF_EXPR
%    D_REF = D_REF_EXPR(I_load,R_L,VD,Vin,Vout,CONVERTER,N_PHASES)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-May-2026 18:13:03

if ~all(cellfun(@isscalar,{converter,n_phases}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((converter == 2.0) & (n_phases == 3.0))
    d_ref = ((Vin.*3.0+sqrt(Vin.^2.*9.0-I_load.*R_L.*VD.*1.2e+1-I_load.*R_L.*Vin.*1.2e+1+I_load.*R_L.*Vout.*1.2e+1)).*(-1.0./6.0))./(VD+Vin-Vout)+1.0;
elseif ((converter == 2.0) & (n_phases == 2.0))
    d_ref = ((Vin+sqrt(Vin.^2-I_load.*R_L.*VD.*2.0-I_load.*R_L.*Vin.*2.0+I_load.*R_L.*Vout.*2.0)).*(-1.0./2.0))./(VD+Vin-Vout)+1.0;
elseif ((converter == 2.0) & (n_phases == 1.0))
    d_ref = ((Vin+sqrt(Vin.^2-I_load.*R_L.*VD.*4.0-I_load.*R_L.*Vin.*4.0+I_load.*R_L.*Vout.*4.0)).*(-1.0./2.0))./(VD+Vin-Vout)+1.0;
elseif ((converter == 0.0) & (n_phases == 3.0))
    d_ref = ((Vin.*3.0+sqrt(Vin.^2.*9.0-I_load.*R_L.*VD.*1.2e+1-I_load.*R_L.*Vout.*1.2e+1)).*(-1.0./6.0))./(VD+Vout)+1.0;
elseif ((converter == 0.0) & (n_phases == 2.0))
    d_ref = ((Vin+sqrt(Vin.^2-I_load.*R_L.*VD.*2.0-I_load.*R_L.*Vout.*2.0)).*(-1.0./2.0))./(VD+Vout)+1.0;
elseif ((converter == 0.0) & (n_phases == 1.0))
    d_ref = ((Vin+sqrt(Vin.^2-I_load.*R_L.*VD.*4.0-I_load.*R_L.*Vout.*4.0)).*(-1.0./2.0))./(VD+Vout)+1.0;
elseif ((converter == 1.0) & (n_phases == 3.0))
    d_ref = (VD+Vout+(I_load.*R_L)./3.0)./(VD+Vin);
elseif ((converter == 1.0) & (n_phases == 2.0))
    d_ref = (VD+Vout+(I_load.*R_L)./2.0)./(VD+Vin);
elseif ((converter == 1.0) & (n_phases == 1.0))
    d_ref = (VD+Vout+I_load.*R_L)./(VD+Vin);
else
    d_ref = 0.0;
end
end
