function duty = duty_cascade_expr(IL,IL_eq_ref,IL_ref_dot,Ki_v,Kp_i,Kp_v,L,R_L,Vin,Vout,Vout_ref,converter,int_eVout)
%DUTY_CASCADE_EXPR
%    DUTY = DUTY_CASCADE_EXPR(IL,IL_eq_ref,IL_ref_dot,Ki_v,Kp_i,Kp_v,L,R_L,Vin,Vout,Vout_ref,CONVERTER,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    13-May-2026 16:59:48

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 2.0)
    duty = -(Vout+IL_ref_dot.*L-IL.*R_L)./(Vin-Vout)-(Kp_i.*L.*(IL-IL_eq_ref+(Ki_v.*int_eVout)./3.0+(Kp_v.*(Vout-Vout_ref))./3.0))./(Vin-Vout);
elseif (converter == 1.0)
    duty = (Vout-IL_ref_dot.*L+IL.*R_L)./Vin-(Kp_i.*L.*(IL-IL_eq_ref+(Ki_v.*int_eVout)./3.0+(Kp_v.*(Vout-Vout_ref))./3.0))./Vin;
elseif (converter == 0.0)
    duty = -(Vin-Vout+IL_ref_dot.*L-IL.*R_L)./Vout-(Kp_i.*L.*(IL-IL_eq_ref+(Ki_v.*int_eVout)./3.0+(Kp_v.*(Vout-Vout_ref))./3.0))./Vout;
else
    duty = 0.0;
end
end
