function duty = duty_cascade_expr(IL,IL_dot,IL_eq_ref,Kp_i,Kp_v,L,R_L,Ti_v,VD,Vin,Vout,Vout_ref,converter,int_eVout)
%DUTY_CASCADE_EXPR
%    DUTY = DUTY_CASCADE_EXPR(IL,IL_dot,IL_eq_ref,Kp_i,Kp_v,L,R_L,Ti_v,VD,Vin,Vout,Vout_ref,CONVERTER,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-May-2026 17:57:26

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    duty = (VD+Vout+IL_dot.*L+IL.*R_L-Kp_i.*L.*(IL-IL_eq_ref+Kp_v.*(Vout-Vout_ref+int_eVout./Ti_v)))./(VD+Vin);
elseif (converter == 0.0)
    duty = -(Vin-IL_dot.*L-IL.*R_L+Kp_i.*L.*(IL-IL_eq_ref+Kp_v.*(Vout-Vout_ref+int_eVout./Ti_v)))./(VD+Vout)+1.0;
else
    duty = 0.0;
end
end
