function B = function_B_0_order(L)
%function_B_0_order
%    B = function_B_0_order(L)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-Jan-2026 14:07:51

t2 = 1.0./L;
B = [t2;t2;t2;0.0];
end
