function Kj_sol = function_Kj(C,L,tau)
%function_Kj
%    Kj_sol = function_Kj(C,L,TAU)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Jan-2026 11:01:42

Kj_sol = (sqrt(3.0).*sqrt(C).*sqrt(L))./(tau.*6.0);
end
