function d_num = function_d_num(C,IL1,IL2,IL3,IL_ref,IL_ref_dot,I_load,Kj,Kr,L,R_ind,Vin,Vout,Vout_ref)
%FUNCTION_D_NUM
%    D_NUM = FUNCTION_D_NUM(C,IL1,IL2,IL3,IL_ref,IL_ref_dot,I_load,Kj,Kr,L,R_ind,Vin,Vout,Vout_ref)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Jan-2026 10:59:43

t2 = Kj.*Vout;
t3 = Kj.*Vout_ref;
t4 = C.^2;
t5 = IL1.^2;
t6 = IL2.^2;
t7 = IL3.^2;
t8 = L.^2;
t9 = L.^3;
t10 = Vout.^2;
t11 = IL1.*IL2;
t12 = IL1.*IL3;
t13 = IL2.*IL3;
t14 = IL_ref_dot.*L;
t15 = IL_ref.*Kr.*R_ind;
t19 = -Vin;
t16 = Vin.*t11;
t17 = Vin.*t12;
t18 = Vin.*t13;
t20 = -t2;
t24 = Vout.*t5;
t25 = Vout.*t6;
t26 = Vout.*t7;
t27 = t3.*t11;
t28 = t3.*t12;
t29 = t3.*t13;
t30 = -t11;
t31 = -t12;
t32 = -t13;
t39 = t3.*t5;
t40 = t3.*t6;
t41 = t3.*t7;
t48 = t5.*t15;
t49 = t6.*t15;
t50 = t7.*t15;
mt1 = [t8.*(t16+t17+t24+t25+t26-t27-t28+t40+t41+t49+t50+t5.*t20+t6.*t19+t6.*t20+t7.*t19+t7.*t20+t15.*t30+t15.*t31-IL1.*I_load.*Vout+IL1.*IL_ref.*t2.*3.0)+IL_ref_dot.*t9.*(t6+t7+t30+t31)+t4.*t10.*(Vout+t3+t14+t15+t19+t20+IL1.*R_ind-IL1.*Kr.*R_ind);t8.*(t16+t18+t24+t25+t26-t27-t29+t39+t41+t48+t50+t5.*t19+t5.*t20+t6.*t20+t7.*t19+t7.*t20+t15.*t30+t15.*t32-IL2.*I_load.*Vout+IL2.*IL_ref.*t2.*3.0)+IL_ref_dot.*t9.*(t5+t7+t30+t32)+t4.*t10.*(Vout+t3+t14+t15+t19+t20+IL2.*R_ind-IL2.*Kr.*R_ind)];
mt2 = [t8.*(t17+t18+t24+t25+t26-t28-t29+t39+t40+t48+t49+t5.*t19+t5.*t20+t6.*t19+t6.*t20+t7.*t20+t15.*t31+t15.*t32-IL3.*I_load.*Vout+IL3.*IL_ref.*t2.*3.0)+IL_ref_dot.*t9.*(t5+t6+t31+t32)+t4.*t10.*(Vout+t3+t14+t15+t19+t20+IL3.*R_ind-IL3.*Kr.*R_ind)];
d_num = [mt1;mt2];
end
