function d_den = function_d_den(C,IL1,IL2,IL3,L,Vout)
%FUNCTION_D_DEN
%    D_DEN = FUNCTION_D_DEN(C,IL1,IL2,IL3,L,Vout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Jan-2026 15:23:30

t2 = C.^2;
t3 = IL1.^2;
t4 = IL2.^2;
t5 = IL3.^2;
t6 = L.^2;
t7 = Vout.^2;
t8 = t3.*t6;
t9 = t4.*t6;
t10 = t5.*t6;
t11 = t2.*t7;
t12 = t8+t9+t10+t11;
t13 = Vout.*t12;
d_den = [t13;t13;t13];
end
