function Kr_sol = function_Kr(L,R_ind,tau)
%function_Kr
%    Kr_sol = function_Kr(L,R_ind,TAU)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Jan-2026 11:01:42

Kr_sol = L./(R_ind.*tau);
end
