function Kr_sol = function_Kr(L,R_ind,tau)
%function_Kr
%    Kr_sol = function_Kr(L,R_ind,TAU)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Dec-2025 08:54:11

Kr_sol = -(R_ind-L.*tau)./R_ind;
end
