function Kj_sol = function_Kj(C,Kr,L,R_ind)
%function_Kj
%    Kj_sol = function_Kj(C,Kr,L,R_ind)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Dec-2025 08:54:11

t2 = sqrt(3.0);
t3 = sqrt(C);
Kj_sol = (1.0./sqrt(L).*(sqrt(L).*-6.0+R_ind.*t2.*t3+Kr.*R_ind.*t2.*t3))./6.0;
end
