function out1 = function_d_den(C,IL1,IL2,IL3,L,Vout)
%FUNCTION_D_DEN
%    OUT1 = FUNCTION_D_DEN(C,IL1,IL2,IL3,L,Vout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Jan-2026 10:59:43

t2 = L.^2;
out1 = Vout.*(IL1.^2.*t2+IL2.^2.*t2+IL3.^2.*t2+C.^2.*Vout.^2);
end
