function A = function_A_0_order(C,D,L,R,R_ind)
%function_A_0_order
%    A = function_A_0_order(C,D,L,R,R_ind)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-Jan-2026 14:07:51

t2 = 1.0./C;
t3 = D-1.0;
t4 = 1.0./L;
t5 = R_ind.*t4;
t7 = t2.*t3;
t8 = t3.*t4;
t6 = -t5;
t9 = -t7;
A = reshape([t6,0.0,0.0,t9,0.0,t6,0.0,t9,0.0,0.0,t6,t9,t8,t8,t8,-t2./R],[4,4]);
end
