function C_mat = function_C_0_order
%function_C_0_order
%    C_mat = function_C_0_order

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-Jan-2026 14:07:51

C_mat = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
end
