function Kp_Ti = gains_cascade_expr(C,IL_eq_ref,Kp_i,L,VD,Vin,Vout_ref,converter,wn_v,zeta_v)
%GAINS_CASCADE_EXPR
%    Kp_Ti = GAINS_CASCADE_EXPR(C,IL_eq_ref,Kp_i,L,VD,Vin,Vout_ref,CONVERTER,WN_V,ZETA_V)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-May-2026 17:57:26

et1 = (IL_eq_ref.*(L.*((C.*VD.^2.*wn_v.^2)./3.0+(C.*Vout_ref.^2.*wn_v.^2)./3.0+C.*VD.*Vout_ref.*wn_v.^2.*(2.0./3.0))-Vin.^2)+C.*VD.^2.*Vin.*wn_v.*zeta_v.*(2.0./3.0)+C.*Vin.*Vout_ref.^2.*wn_v.*zeta_v.*(2.0./3.0)+C.*VD.*Vin.*Vout_ref.*wn_v.*zeta_v.*(4.0./3.0))./((VD+Vout_ref).*(Vin.^2+IL_eq_ref.^2.*L.^2.*wn_v.^2+IL_eq_ref.*L.*Vin.*wn_v.*zeta_v.*2.0));
et2 = -(IL_eq_ref.*Vin.^2.*wn_v.*zeta_v.*-2.0-IL_eq_ref.^2.*L.*Vin.*wn_v.^2-(C.*VD.^2.*Vin.*wn_v.^2)./3.0-(C.*Vin.*Vout_ref.^2.*wn_v.^2)./3.0+C.*VD.^2.*Vin.*wn_v.^2.*zeta_v.^2.*(4.0./3.0)+C.*Vin.*Vout_ref.^2.*wn_v.^2.*zeta_v.^2.*(4.0./3.0)-C.*VD.*Vin.*Vout_ref.*wn_v.^2.*(2.0./3.0)+C.*IL_eq_ref.*L.*VD.^2.*wn_v.^3.*zeta_v.*(2.0./3.0)+C.*IL_eq_ref.*L.*Vout_ref.^2.*wn_v.^3.*zeta_v.*(2.0./3.0)+C.*VD.*Vin.*Vout_ref.*wn_v.^2.*zeta_v.^2.*(8.0./3.0)+C.*IL_eq_ref.*L.*VD.*Vout_ref.*wn_v.^3.*zeta_v.*(4.0./3.0))./(Kp_i.*(VD+Vout_ref).*(Vin.^2+IL_eq_ref.^2.*L.^2.*wn_v.^2+IL_eq_ref.*L.*Vin.*wn_v.*zeta_v.*2.0));
et3 = 1.0./wn_v.^2.*(wn_v.*(IL_eq_ref.*Vin.^2.*zeta_v.*6.0+C.*Kp_i.*VD.^2.*Vin.*zeta_v.*2.0+C.*Kp_i.*Vin.*Vout_ref.^2.*zeta_v.*2.0+C.*Kp_i.*VD.*Vin.*Vout_ref.*zeta_v.*4.0)+wn_v.^2.*(IL_eq_ref.^2.*L.*Vin.*3.0+C.*VD.^2.*Vin+C.*Vin.*Vout_ref.^2-C.*VD.^2.*Vin.*zeta_v.^2.*4.0-C.*Vin.*Vout_ref.^2.*zeta_v.^2.*4.0+C.*VD.*Vin.*Vout_ref.*2.0+C.*IL_eq_ref.*Kp_i.*L.*VD.^2+C.*IL_eq_ref.*Kp_i.*L.*Vout_ref.^2-C.*VD.*Vin.*Vout_ref.*zeta_v.^2.*8.0+C.*IL_eq_ref.*Kp_i.*L.*VD.*Vout_ref.*2.0)-wn_v.^3.*(C.*IL_eq_ref.*L.*VD.^2.*zeta_v.*2.0+C.*IL_eq_ref.*L.*Vout_ref.^2.*zeta_v.*2.0+C.*IL_eq_ref.*L.*VD.*Vout_ref.*zeta_v.*4.0)-IL_eq_ref.*Kp_i.*Vin.^2.*3.0);
et4 = -1.0./(IL_eq_ref.*Vin.^2.*-3.0-IL_eq_ref.^2.*Kp_i.*L.*Vin.*3.0-C.*Kp_i.*VD.^2.*Vin-C.*Kp_i.*Vin.*Vout_ref.^2+C.*VD.^2.*Vin.*wn_v.*zeta_v.*2.0+C.*Vin.*Vout_ref.^2.*wn_v.*zeta_v.*2.0+C.*IL_eq_ref.*L.*VD.^2.*wn_v.^2+C.*IL_eq_ref.*L.*Vout_ref.^2.*wn_v.^2-C.*Kp_i.*VD.*Vin.*Vout_ref.*2.0+C.*VD.*Vin.*Vout_ref.*wn_v.*zeta_v.*4.0+C.*IL_eq_ref.*L.*VD.*Vout_ref.*wn_v.^2.*2.0);
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t0 = C.*wn_v.*zeta_v.*(2.0./3.0)-(C.*wn_v.^2.*(zeta_v.^2.*4.0-1.0))./(Kp_i.*3.0);
elseif (converter == 0.0)
    t0 = et1+et2;
else
    t0 = 0.0;
end
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t1 = 1.0./(Kp_i-wn_v.*zeta_v.*2.0)+(zeta_v.*2.0)./wn_v;
elseif (converter == 0.0)
    t1 = et3.*et4;
else
    t1 = 0.0;
end
Kp_Ti = [t0,t1];
end
