function Kp_Ki = gains_cascade_expr(C,IL_eq_ref,Kp_i,L,VD,Vin,Vout_ref,converter,wn_v,zeta_v)
%GAINS_CASCADE_EXPR
%    Kp_Ki = GAINS_CASCADE_EXPR(C,IL_eq_ref,Kp_i,L,VD,Vin,Vout_ref,CONVERTER,WN_V,ZETA_V)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    13-May-2026 16:59:48

et1 = (IL_eq_ref.*((VD+Vin).^2.*3.0+L.*(C.*Vout_ref.^2.*wn_v.^2+C.*wn_v.^2.*(VD+Vin).^2-C.*Vout_ref.*wn_v.^2.*(VD+Vin).*2.0))+C.*wn_v.*zeta_v.*(VD+Vin).^3.*2.0-C.*Vout_ref.*wn_v.*zeta_v.*(VD+Vin).^2.*4.0+C.*Vout_ref.^2.*wn_v.*zeta_v.*(VD+Vin).*2.0)./(((VD+Vin).^2+IL_eq_ref.^2.*L.^2.*wn_v.^2+IL_eq_ref.*L.*wn_v.*zeta_v.*(VD+Vin).*2.0).*(VD+Vin-Vout_ref));
et2 = -(-C.*wn_v.^2.*(VD+Vin).^3+IL_eq_ref.*wn_v.*zeta_v.*(VD+Vin).^2.*6.0+IL_eq_ref.^2.*L.*wn_v.^2.*(VD+Vin).*3.0+C.*Vout_ref.*wn_v.^2.*(VD+Vin).^2.*2.0-C.*Vout_ref.^2.*wn_v.^2.*(VD+Vin)+C.*wn_v.^2.*zeta_v.^2.*(VD+Vin).^3.*4.0-C.*Vout_ref.*wn_v.^2.*zeta_v.^2.*(VD+Vin).^2.*8.0+C.*Vout_ref.^2.*wn_v.^2.*zeta_v.^2.*(VD+Vin).*4.0+C.*IL_eq_ref.*L.*Vout_ref.^2.*wn_v.^3.*zeta_v.*2.0+C.*IL_eq_ref.*L.*wn_v.^3.*zeta_v.*(VD+Vin).^2.*2.0-C.*IL_eq_ref.*L.*Vout_ref.*wn_v.^3.*zeta_v.*(VD+Vin).*4.0)./(Kp_i.*((VD+Vin).^2+IL_eq_ref.^2.*L.^2.*wn_v.^2+IL_eq_ref.*L.*wn_v.*zeta_v.*(VD+Vin).*2.0).*(VD+Vin-Vout_ref));
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 2.0)
    t0 = et1+et2;
elseif (converter == 1.0)
    t0 = C.*wn_v.*zeta_v.*2.0-(C.*wn_v.^2.*(zeta_v.^2.*4.0-1.0))./Kp_i;
elseif (converter == 0.0)
    t0 = (Vin.*3.0)./(Kp_i.*L.*(VD+Vout_ref))-(IL_eq_ref.*(Kp_i.*Vin.^2.*3.0-L.*(C.*Kp_i.*wn_v.^2.*(VD+Vout_ref).^2-C.*wn_v.^3.*zeta_v.*(VD+Vout_ref).^2.*2.0))+(Vin.^3.*3.0)./L-C.*Vin.*wn_v.^2.*(VD+Vout_ref).^2+C.*Vin.*wn_v.^2.*zeta_v.^2.*(VD+Vout_ref).^2.*4.0-C.*Kp_i.*Vin.*wn_v.*zeta_v.*(VD+Vout_ref).^2.*2.0)./(Kp_i.*(VD+Vout_ref).*(Vin.^2+IL_eq_ref.^2.*L.^2.*wn_v.^2+IL_eq_ref.*L.*Vin.*wn_v.*zeta_v.*2.0));
else
    t0 = 0.0;
end
mt1 = [t0];
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 2.0)
    t0 = -(wn_v.^2.*(IL_eq_ref.*(VD+Vin).^2.*3.0-C.*Kp_i.*(VD+Vin).^3+C.*Kp_i.*Vout_ref.*(VD+Vin).^2.*2.0-C.*Kp_i.*Vout_ref.^2.*(VD+Vin)+C.*wn_v.*zeta_v.*(VD+Vin).^3.*2.0-C.*Vout_ref.*wn_v.*zeta_v.*(VD+Vin).^2.*4.0+C.*Vout_ref.^2.*wn_v.*zeta_v.*(VD+Vin).*2.0)+L.*wn_v.^2.*(IL_eq_ref.^2.*Kp_i.*(VD+Vin).*3.0+C.*IL_eq_ref.*wn_v.^2.*(VD+Vin).^2+C.*IL_eq_ref.*Vout_ref.^2.*wn_v.^2-C.*IL_eq_ref.*Vout_ref.*wn_v.^2.*(VD+Vin).*2.0))./(Kp_i.*((VD+Vin).^2+IL_eq_ref.^2.*L.^2.*wn_v.^2+IL_eq_ref.*L.*wn_v.*zeta_v.*(VD+Vin).*2.0).*(VD+Vin-Vout_ref));
elseif (converter == 1.0)
    t0 = (C.*wn_v.^2.*(Kp_i-wn_v.*zeta_v.*2.0))./Kp_i;
elseif (converter == 0.0)
    t0 = (wn_v.^2.*(IL_eq_ref.*Vin.^2.*3.0+C.*Kp_i.*Vin.*(VD+Vout_ref).^2-C.*Vin.*wn_v.*zeta_v.*(VD+Vout_ref).^2.*2.0)+IL_eq_ref.*L.*wn_v.^2.*(IL_eq_ref.*Kp_i.*Vin.*3.0-C.*wn_v.^2.*(VD+Vout_ref).^2))./(Kp_i.*(VD+Vout_ref).*(Vin.^2+IL_eq_ref.^2.*L.^2.*wn_v.^2+IL_eq_ref.*L.*Vin.*wn_v.*zeta_v.*2.0));
else
    t0 = 0.0;
end
mt2 = [t0];
Kp_Ki = [mt1,mt2];
end
