function gains_expr = IDAPBC_gains(C,L,R_L,converter,k,ts,zeta)
%IDAPBC_gains
%    GAINS_EXPR = IDAPBC_gains(C,L,R_L,CONVERTER,K,TS,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Jul-2026 10:57:35

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((converter == 0.0) | (converter == 1.0))
    t0 = (sqrt(C).*sqrt(L).*sqrt(((k.*-2.0+k.*zeta.^2.*4.0+k.^2+1.0).*(-6.4e+1./3.0))./(k-1.0)))./(ts.*zeta.*2.0);
else
    t0 = 1.0;
end
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((converter == 0.0) | (converter == 1.0))
    t1 = (L.*8.0)./(R_L.*ts-R_L.*k.*ts);
else
    t1 = 1.0;
end
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t2 = k.*1.0./ts.^2.*1.0./zeta.^2.*1.6e+1;
elseif ((converter == 0.0) | (converter == 1.0))
    t2 = (L.*8.0)./(R_L.*ts-R_L.*k.*ts);
else
    t2 = 1.0;
end
gains_expr = [t0;t1;t2];
end
