function [d_num,d_den] = IDAPBC_duty_Buck(IL1,IL2,IL3,Ki,Kj,Kr,L,R_L,VD,Vin,Vout,int_eVout)
%IDAPBC_duty_Buck
%    [D_NUM,D_DEN] = IDAPBC_duty_Buck(IL1,IL2,IL3,Ki,Kj,Kr,L,R_L,VD,Vin,Vout,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Jul-2026 11:11:17

d_num = [VD+Vout-Kj.*Vout+IL1.*R_L-IL1.*Kr.*R_L-Ki.*L.*int_eVout;VD+Vout-Kj.*Vout+IL2.*R_L-IL2.*Kr.*R_L-Ki.*L.*int_eVout;VD+Vout-Kj.*Vout+IL3.*R_L-IL3.*Kr.*R_L-Ki.*L.*int_eVout];
if nargout > 1
    d_den = VD+Vin;
end
end
