function duty = IDAPBC_expr(IL1,IL_ref_dot,Kj,Kr,L,R_L,VD,Vin,Vout,converter,e_IL1,e_Vout)
%IDAPBC_expr
%    DUTY = IDAPBC_expr(IL1,IL_ref_dot,Kj,Kr,L,R_L,VD,Vin,Vout,CONVERTER,e_IL1,e_Vout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    30-Apr-2026 11:23:24

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 0.0)
    duty = (VD-Vin+Vout-Kj.*e_Vout+IL_ref_dot.*L+IL1.*R_L-Kr.*R_L.*e_IL1)./(VD+Vout);
else
    duty = 0.0;
end
end
