function [d_num,d_den] = IDAPBC_duty_Boost(C,IL1,IL2,IL3,I_load,Ki,Kj,Kr,L,R_L,VD,Vin,Vout,int_eVout)
%IDAPBC_duty_Boost
%    [D_NUM,D_DEN] = IDAPBC_duty_Boost(C,IL1,IL2,IL3,I_load,Ki,Kj,Kr,L,R_L,VD,Vin,Vout,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Jul-2026 11:11:15

et1 = C.^2.*VD.^3+C.^2.*Vout.^3-C.^2.*Kj.*Vout.^3+IL1.^2.*L.^2.*VD+IL2.^2.*L.^2.*VD+IL3.^2.*L.^2.*VD-IL1.^2.*L.^2.*Vin-IL2.^2.*L.^2.*Vin+IL1.^2.*L.^2.*Vout+IL2.^2.*L.^2.*Vout+IL3.^2.*L.^2.*Vout-C.^2.*VD.^2.*Vin+C.^2.*VD.*Vout.^2.*3.0+C.^2.*VD.^2.*Vout.*3.0-C.^2.*Vin.*Vout.^2-C.^2.*VD.*Vin.*Vout.*2.0+C.^2.*IL3.*R_L.*VD.^2+C.^2.*IL3.*R_L.*Vout.^2-IL3.^2.*Kj.*L.^2.*VD-IL1.^2.*Kj.*L.^2.*Vout-IL2.^2.*Kj.*L.^2.*Vout;
et2 = -IL3.^2.*Kj.*L.^2.*Vout-C.^2.*Kj.*VD.*Vout.^2.*2.0-C.^2.*Kj.*VD.^2.*Vout-IL1.^2.*Ki.*L.^3.*int_eVout-IL2.^2.*Ki.*L.^3.*int_eVout-IL3.*I_load.*L.^2.*VD+IL1.*IL3.*L.^2.*Vin+IL2.*IL3.*L.^2.*Vin-IL3.*I_load.*L.^2.*Vout-IL1.*IL3.*Kj.*L.^2.*VD-IL2.*IL3.*Kj.*L.^2.*VD+C.^2.*IL3.*R_L.*VD.*Vout.*2.0+IL1.*IL3.*Ki.*L.^3.*int_eVout+IL2.*IL3.*Ki.*L.^3.*int_eVout-C.^2.*IL3.*Kr.*R_L.*VD.^2-C.^2.*IL3.*Kr.*R_L.*Vout.^2-C.^2.*Ki.*L.*VD.^2.*int_eVout-C.^2.*Ki.*L.*Vout.^2.*int_eVout-C.^2.*IL3.*Kr.*R_L.*VD.*Vout.*2.0;
et3 = C.^2.*Ki.*L.*VD.*Vout.*int_eVout.*-2.0;
et4 = C.^2.*VD.^3+C.^2.*Vout.^3-C.^2.*Kj.*Vout.^3+IL1.^2.*L.^2.*VD+IL2.^2.*L.^2.*VD+IL3.^2.*L.^2.*VD-IL1.^2.*L.^2.*Vin-IL3.^2.*L.^2.*Vin+IL1.^2.*L.^2.*Vout+IL2.^2.*L.^2.*Vout+IL3.^2.*L.^2.*Vout-C.^2.*VD.^2.*Vin+C.^2.*VD.*Vout.^2.*3.0+C.^2.*VD.^2.*Vout.*3.0-C.^2.*Vin.*Vout.^2-C.^2.*VD.*Vin.*Vout.*2.0+C.^2.*IL2.*R_L.*VD.^2+C.^2.*IL2.*R_L.*Vout.^2-IL2.^2.*Kj.*L.^2.*VD-IL1.^2.*Kj.*L.^2.*Vout-IL2.^2.*Kj.*L.^2.*Vout;
et5 = -IL3.^2.*Kj.*L.^2.*Vout-C.^2.*Kj.*VD.*Vout.^2.*2.0-C.^2.*Kj.*VD.^2.*Vout-IL1.^2.*Ki.*L.^3.*int_eVout-IL3.^2.*Ki.*L.^3.*int_eVout-IL2.*I_load.*L.^2.*VD+IL1.*IL2.*L.^2.*Vin+IL2.*IL3.*L.^2.*Vin-IL2.*I_load.*L.^2.*Vout-IL1.*IL2.*Kj.*L.^2.*VD-IL2.*IL3.*Kj.*L.^2.*VD+C.^2.*IL2.*R_L.*VD.*Vout.*2.0+IL1.*IL2.*Ki.*L.^3.*int_eVout+IL2.*IL3.*Ki.*L.^3.*int_eVout-C.^2.*IL2.*Kr.*R_L.*VD.^2-C.^2.*IL2.*Kr.*R_L.*Vout.^2-C.^2.*Ki.*L.*VD.^2.*int_eVout-C.^2.*Ki.*L.*Vout.^2.*int_eVout-C.^2.*IL2.*Kr.*R_L.*VD.*Vout.*2.0;
et6 = C.^2.*Ki.*L.*VD.*Vout.*int_eVout.*-2.0;
et7 = C.^2.*VD.^3+C.^2.*Vout.^3-C.^2.*Kj.*Vout.^3+IL1.^2.*L.^2.*VD+IL2.^2.*L.^2.*VD+IL3.^2.*L.^2.*VD-IL2.^2.*L.^2.*Vin-IL3.^2.*L.^2.*Vin+IL1.^2.*L.^2.*Vout+IL2.^2.*L.^2.*Vout+IL3.^2.*L.^2.*Vout-C.^2.*VD.^2.*Vin+C.^2.*VD.*Vout.^2.*3.0+C.^2.*VD.^2.*Vout.*3.0-C.^2.*Vin.*Vout.^2-C.^2.*VD.*Vin.*Vout.*2.0+C.^2.*IL1.*R_L.*VD.^2+C.^2.*IL1.*R_L.*Vout.^2-IL1.^2.*Kj.*L.^2.*VD-IL1.^2.*Kj.*L.^2.*Vout-IL2.^2.*Kj.*L.^2.*Vout;
et8 = -IL3.^2.*Kj.*L.^2.*Vout-C.^2.*Kj.*VD.*Vout.^2.*2.0-C.^2.*Kj.*VD.^2.*Vout-IL2.^2.*Ki.*L.^3.*int_eVout-IL3.^2.*Ki.*L.^3.*int_eVout-IL1.*I_load.*L.^2.*VD+IL1.*IL2.*L.^2.*Vin+IL1.*IL3.*L.^2.*Vin-IL1.*I_load.*L.^2.*Vout-IL1.*IL2.*Kj.*L.^2.*VD-IL1.*IL3.*Kj.*L.^2.*VD+C.^2.*IL1.*R_L.*VD.*Vout.*2.0+IL1.*IL2.*Ki.*L.^3.*int_eVout+IL1.*IL3.*Ki.*L.^3.*int_eVout-C.^2.*IL1.*Kr.*R_L.*VD.^2-C.^2.*IL1.*Kr.*R_L.*Vout.^2-C.^2.*Ki.*L.*VD.^2.*int_eVout-C.^2.*Ki.*L.*Vout.^2.*int_eVout-C.^2.*IL1.*Kr.*R_L.*VD.*Vout.*2.0;
et9 = C.^2.*Ki.*L.*VD.*Vout.*int_eVout.*-2.0;
d_num = [et7+et8+et9;et4+et5+et6;et1+et2+et3];
if nargout > 1
    d_den = (VD+Vout).*(IL1.^2.*L.^2+IL2.^2.*L.^2+IL3.^2.*L.^2+C.^2.*VD.^2+C.^2.*Vout.^2+C.^2.*VD.*Vout.*2.0);
end
end
