function [d_num,d_den] = IDAPBC_duty(C,IL1,IL2,IL3,I_load,Ki,Kj,Kr,L,R_L,VD,Vin,Vout,converter,int_eVout)
%IDAPBC_duty
%    [D_NUM,D_DEN] = IDAPBC_duty(C,IL1,IL2,IL3,I_load,Ki,Kj,Kr,L,R_L,VD,Vin,Vout,CONVERTER,int_eVout)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Jul-2026 10:57:35

et1 = C.^2.*VD.^3+C.^2.*Vout.^3-C.^2.*Kj.*Vout.^3+IL1.^2.*L.^2.*VD+IL2.^2.*L.^2.*VD+IL3.^2.*L.^2.*VD-IL1.^2.*L.^2.*Vin-IL2.^2.*L.^2.*Vin+IL1.^2.*L.^2.*Vout+IL2.^2.*L.^2.*Vout+IL3.^2.*L.^2.*Vout-C.^2.*VD.^2.*Vin+C.^2.*VD.*Vout.^2.*3.0+C.^2.*VD.^2.*Vout.*3.0-C.^2.*Vin.*Vout.^2-C.^2.*VD.*Vin.*Vout.*2.0+C.^2.*IL3.*R_L.*VD.^2+C.^2.*IL3.*R_L.*Vout.^2-IL3.^2.*Kj.*L.^2.*VD-IL1.^2.*Kj.*L.^2.*Vout-IL2.^2.*Kj.*L.^2.*Vout;
et2 = -IL3.^2.*Kj.*L.^2.*Vout-C.^2.*Kj.*VD.*Vout.^2.*2.0-C.^2.*Kj.*VD.^2.*Vout-IL3.*I_load.*L.^2.*VD+IL1.*IL3.*L.^2.*Vin+IL2.*IL3.*L.^2.*Vin-IL3.*I_load.*L.^2.*Vout-IL1.*IL3.*Kj.*L.^2.*VD-IL2.*IL3.*Kj.*L.^2.*VD+C.^2.*IL3.*R_L.*VD.*Vout.*2.0-C.^2.*IL3.*Kr.*R_L.*VD.^2-C.^2.*IL3.*Kr.*R_L.*Vout.^2-C.^2.*IL3.*Kr.*R_L.*VD.*Vout.*2.0+C.*IL3.*Ki.*L.^2.*VD.*int_eVout+C.*IL3.*Ki.*L.^2.*Vout.*int_eVout;
et3 = C.^2.*VD.^3+C.^2.*Vout.^3-C.^2.*Kj.*Vout.^3+IL1.^2.*L.^2.*VD+IL2.^2.*L.^2.*VD+IL3.^2.*L.^2.*VD-IL1.^2.*L.^2.*Vin-IL3.^2.*L.^2.*Vin+IL1.^2.*L.^2.*Vout+IL2.^2.*L.^2.*Vout+IL3.^2.*L.^2.*Vout-C.^2.*VD.^2.*Vin+C.^2.*VD.*Vout.^2.*3.0+C.^2.*VD.^2.*Vout.*3.0-C.^2.*Vin.*Vout.^2-C.^2.*VD.*Vin.*Vout.*2.0+C.^2.*IL2.*R_L.*VD.^2+C.^2.*IL2.*R_L.*Vout.^2-IL2.^2.*Kj.*L.^2.*VD-IL1.^2.*Kj.*L.^2.*Vout-IL2.^2.*Kj.*L.^2.*Vout;
et4 = -IL3.^2.*Kj.*L.^2.*Vout-C.^2.*Kj.*VD.*Vout.^2.*2.0-C.^2.*Kj.*VD.^2.*Vout-IL2.*I_load.*L.^2.*VD+IL1.*IL2.*L.^2.*Vin+IL2.*IL3.*L.^2.*Vin-IL2.*I_load.*L.^2.*Vout-IL1.*IL2.*Kj.*L.^2.*VD-IL2.*IL3.*Kj.*L.^2.*VD+C.^2.*IL2.*R_L.*VD.*Vout.*2.0-C.^2.*IL2.*Kr.*R_L.*VD.^2-C.^2.*IL2.*Kr.*R_L.*Vout.^2-C.^2.*IL2.*Kr.*R_L.*VD.*Vout.*2.0+C.*IL2.*Ki.*L.^2.*VD.*int_eVout+C.*IL2.*Ki.*L.^2.*Vout.*int_eVout;
et5 = C.^2.*VD.^3+C.^2.*Vout.^3-C.^2.*Kj.*Vout.^3+IL1.^2.*L.^2.*VD+IL2.^2.*L.^2.*VD+IL3.^2.*L.^2.*VD-IL2.^2.*L.^2.*Vin-IL3.^2.*L.^2.*Vin+IL1.^2.*L.^2.*Vout+IL2.^2.*L.^2.*Vout+IL3.^2.*L.^2.*Vout-C.^2.*VD.^2.*Vin+C.^2.*VD.*Vout.^2.*3.0+C.^2.*VD.^2.*Vout.*3.0-C.^2.*Vin.*Vout.^2-C.^2.*VD.*Vin.*Vout.*2.0+C.^2.*IL1.*R_L.*VD.^2+C.^2.*IL1.*R_L.*Vout.^2-IL1.^2.*Kj.*L.^2.*VD-IL1.^2.*Kj.*L.^2.*Vout-IL2.^2.*Kj.*L.^2.*Vout;
et6 = -IL3.^2.*Kj.*L.^2.*Vout-C.^2.*Kj.*VD.*Vout.^2.*2.0-C.^2.*Kj.*VD.^2.*Vout-IL1.*I_load.*L.^2.*VD+IL1.*IL2.*L.^2.*Vin+IL1.*IL3.*L.^2.*Vin-IL1.*I_load.*L.^2.*Vout-IL1.*IL2.*Kj.*L.^2.*VD-IL1.*IL3.*Kj.*L.^2.*VD+C.^2.*IL1.*R_L.*VD.*Vout.*2.0-C.^2.*IL1.*Kr.*R_L.*VD.^2-C.^2.*IL1.*Kr.*R_L.*Vout.^2-C.^2.*IL1.*Kr.*R_L.*VD.*Vout.*2.0+C.*IL1.*Ki.*L.^2.*VD.*int_eVout+C.*IL1.*Ki.*L.^2.*Vout.*int_eVout;
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t0 = VD+Vout-Kj.*Vout+IL1.*R_L-IL1.*Kr.*R_L;
elseif (converter == 0.0)
    t0 = et5+et6;
else
    t0 = 0.0;
end
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t1 = VD+Vout-Kj.*Vout+IL2.*R_L-IL2.*Kr.*R_L;
elseif (converter == 0.0)
    t1 = et3+et4;
else
    t1 = 0.0;
end
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t2 = VD+Vout-Kj.*Vout+IL3.*R_L-IL3.*Kr.*R_L;
elseif (converter == 0.0)
    t2 = et1+et2;
else
    t2 = 0.0;
end
d_num = [t0;t1;t2];
if nargout > 1
    if ~all(cellfun(@isscalar,{converter}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (converter == 1.0)    d_den = VD+Vin;elseif (converter == 0.0)    d_den = (VD+Vout).*(IL1.^2.*L.^2+IL2.^2.*L.^2+IL3.^2.*L.^2+C.^2.*VD.^2+C.^2.*Vout.^2+C.^2.*VD.*Vout.*2.0);else    d_den = 1.0;end;
end
end
