function IL_ref = IL_ref_expr(I_load,R_L,VD,Vin,Vout,converter,n_phases)
%IL_ref_expr
%    IL_ref = IL_ref_expr(I_load,R_L,VD,Vin,Vout,CONVERTER,N_PHASES)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-May-2026 18:13:02

if ~all(cellfun(@isscalar,{converter,n_phases}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((converter == 2.0) & (n_phases == 3.0))
    IL_ref = (Vin.*3.0-sqrt(3.0).*sqrt(Vin.^2.*3.0-I_load.*R_L.*VD.*4.0-I_load.*R_L.*Vin.*4.0+I_load.*R_L.*Vout.*4.0))./(R_L.*6.0);
elseif ((converter == 2.0) & (n_phases == 2.0))
    IL_ref = (Vin-sqrt(Vin.^2-I_load.*R_L.*VD.*2.0-I_load.*R_L.*Vin.*2.0+I_load.*R_L.*Vout.*2.0))./(R_L.*2.0);
elseif ((converter == 2.0) & (n_phases == 1.0))
    IL_ref = (Vin-sqrt(Vin.^2-I_load.*R_L.*VD.*4.0-I_load.*R_L.*Vin.*4.0+I_load.*R_L.*Vout.*4.0))./(R_L.*2.0);
elseif ((converter == 0.0) & (n_phases == 3.0))
    IL_ref = (Vin.*3.0-sqrt(3.0).*sqrt(Vin.^2.*3.0-I_load.*R_L.*VD.*4.0-I_load.*R_L.*Vout.*4.0))./(R_L.*6.0);
elseif ((converter == 0.0) & (n_phases == 2.0))
    IL_ref = (Vin-sqrt(Vin.^2-I_load.*R_L.*VD.*2.0-I_load.*R_L.*Vout.*2.0))./(R_L.*2.0);
elseif ((converter == 0.0) & (n_phases == 1.0))
    IL_ref = (Vin-sqrt(Vin.^2-I_load.*R_L.*VD.*4.0-I_load.*R_L.*Vout.*4.0))./(R_L.*2.0);
elseif ((converter == 1.0) & (n_phases == 3.0))
    IL_ref = I_load./3.0;
elseif ((converter == 1.0) & (n_phases == 2.0))
    IL_ref = I_load./2.0;
elseif ((converter == 1.0) & (n_phases == 1.0))
    IL_ref = I_load;
else
    IL_ref = 0.0;
end
end
