function d_dot = Krasovskii_duty(IL,IL_ref,IL_dot,K_u,Kp_i,Kp_v,VD,Vin,Vout,Vout_ref,Vout_dot,converter)
%Krasovskii_duty
%    D_DOT = Krasovskii_duty(IL,IL_ref,IL_dot,K_u,Kp_i,Kp_v,VD,Vin,Vout,Vout_ref,Vout_dot,CONVERTER)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Jul-2026 10:57:00

if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    d_dot = -K_u.*(IL_dot.*VD+IL_dot.*Vin)-Kp_v.*(Vout-Vout_ref)-Kp_i.*(IL-IL_ref);
elseif (converter == 0.0)
    d_dot = K_u.*(IL_dot.*VD-IL.*Vout_dot+IL_dot.*Vout)-Kp_v.*(Vout-Vout_ref)-Kp_i.*(IL-IL_ref);
else
    d_dot = 0.0;
end
end
