function d_dot = Krasovskii_duty_Boost(IL,IL_ref,IL_dot,K_u,Kp_i,Kp_v,VD,Vout,Vout_ref,Vout_dot)
%Krasovskii_duty_Boost
%    D_DOT = Krasovskii_duty_Boost(IL,IL_ref,IL_dot,K_u,Kp_i,Kp_v,VD,Vout,Vout_ref,Vout_dot)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Jul-2026 14:26:55

d_dot = K_u.*(IL_dot.*VD-IL.*Vout_dot+IL_dot.*Vout)-Kp_v.*(Vout-Vout_ref)-Kp_i.*(IL-IL_ref);
end
