function gains_expr = Krasovskii_gains(C,IL_ref,L,R_L,Vin,Vout_ref,converter,d_ref,k,ts,zeta)
%Krasovskii_gains
%    GAINS_EXPR = Krasovskii_gains(C,IL_ref,L,R_L,Vin,Vout_ref,CONVERTER,D_REF,K,TS,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Jul-2026 10:57:12

et1 = C.*IL_ref.^3.*L.^3.*k.*3.84e+2+C.^2.*IL_ref.*L.^2.*Vout_ref.^2.*k.*1.28e+2-C.*IL_ref.^3.*R_L.^3.*ts.^3.*zeta.^2.*3.0-C.*IL_ref.^3.*L.^2.*R_L.*ts.*4.8e+1-C.*Vout_ref.^3.*d_ref.^3.*ts.^3.*zeta.^2.*3.0+C.^2.*L.*Vout_ref.^3.*d_ref.*ts.*1.6e+1-C.^2.*IL_ref.*L.*R_L.*Vout_ref.^2.*ts.*1.6e+1+C.*IL_ref.^3.*R_L.^3.*k.*ts.^3.*zeta.^2.*3.0+IL_ref.^3.*L.*R_L.*d_ref.^2.*ts.^3.*zeta.^2.*9.0-IL_ref.^2.*L.*Vout_ref.*d_ref.^3.*ts.^3.*zeta.^2.*9.0+C.*IL_ref.^2.*L.^2.*Vout_ref.*d_ref.*ts.*4.8e+1+C.*IL_ref.^3.*L.^2.*R_L.*k.*ts.*4.8e+1+C.*Vout_ref.^3.*d_ref.^3.*k.*ts.^3.*zeta.^2.*3.0;
et2 = C.^2.*L.*Vout_ref.^3.*d_ref.*k.*ts.*-1.6e+1+C.*IL_ref.^3.*L.*R_L.^2.*ts.^2.*zeta.^2.*2.4e+1-C.*IL_ref.^3.*L.^2.*R_L.*k.*ts.*zeta.^2.*1.92e+2+C.^2.*L.*Vout_ref.^3.*d_ref.*k.*ts.*zeta.^2.*6.4e+1+C.*IL_ref.*R_L.*Vout_ref.^2.*d_ref.^2.*ts.^3.*zeta.^2.*3.0+C.*IL_ref.^2.*R_L.^2.*Vout_ref.*d_ref.*ts.^3.*zeta.^2.*3.0+C.^2.*IL_ref.*L.*R_L.*Vout_ref.^2.*k.*ts.*1.6e+1-IL_ref.^3.*L.*R_L.*d_ref.^2.*k.*ts.^3.*zeta.^2.*9.0+IL_ref.^2.*L.*Vout_ref.*d_ref.^3.*k.*ts.^3.*zeta.^2.*9.0-C.*IL_ref.^2.*L.^2.*Vout_ref.*d_ref.*k.*ts.*4.8e+1-C.*IL_ref.^2.*L.*R_L.*Vout_ref.*d_ref.*ts.^2.*zeta.^2.*2.4e+1;
et3 = C.^2.*IL_ref.*L.*R_L.*Vout_ref.^2.*k.*ts.*zeta.^2.*-6.4e+1+C.*IL_ref.^2.*L.^2.*Vout_ref.*d_ref.*k.*ts.*zeta.^2.*1.92e+2-C.*IL_ref.*R_L.*Vout_ref.^2.*d_ref.^2.*k.*ts.^3.*zeta.^2.*3.0-C.*IL_ref.^2.*R_L.^2.*Vout_ref.*d_ref.*k.*ts.^3.*zeta.^2.*3.0;
et4 = C.^3.*L.*Vout_ref.^3.*k.*1.28e+2+C.^2.*IL_ref.^2.*L.^2.*Vout_ref.*k.*3.84e+2+IL_ref.^3.*L.*d_ref.^3.*ts.^3.*zeta.^2.*2.7e+1-C.*IL_ref.^3.*L.^2.*d_ref.*ts.*1.44e+2-C.*IL_ref.^3.*R_L.^2.*d_ref.*ts.^3.*zeta.^2.*9.0+C.*IL_ref.*Vout_ref.^2.*d_ref.^3.*ts.^3.*zeta.^2.*9.0-C.^2.*IL_ref.*L.*Vout_ref.^2.*d_ref.*ts.*4.8e+1-IL_ref.^3.*L.*d_ref.^3.*k.*ts.^3.*zeta.^2.*2.7e+1+C.*IL_ref.^3.*L.^2.*d_ref.*k.*ts.*1.44e+2-C.*IL_ref.^3.*L.^2.*d_ref.*k.*ts.*zeta.^2.*5.76e+2+C.*IL_ref.^3.*R_L.^2.*d_ref.*k.*ts.^3.*zeta.^2.*9.0-C.*IL_ref.*Vout_ref.^2.*d_ref.^3.*k.*ts.^3.*zeta.^2.*9.0;
et5 = C.^2.*IL_ref.*L.*Vout_ref.^2.*d_ref.*k.*ts.*4.8e+1+C.*IL_ref.^3.*L.*R_L.*d_ref.*ts.^2.*zeta.^2.*7.2e+1-C.^2.*IL_ref.*L.*Vout_ref.^2.*d_ref.*k.*ts.*zeta.^2.*1.92e+2;
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t0 = (L.*8.0-R_L.*ts+R_L.*k.*ts)./(Vin.^2.*ts-Vin.^2.*k.*ts);
elseif (converter == 0.0)
    t0 = (C.*L.*8.0-C.*R_L.*ts+C.*R_L.*k.*ts)./(IL_ref.^2.*L.*ts.*3.0+C.*Vout_ref.^2.*ts-IL_ref.^2.*L.*k.*ts.*3.0-C.*Vout_ref.^2.*k.*ts);
else
    t0 = 0.0;
end
mt1 = [t0];
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t0 = (C.*L.*k.*1.28e+2)./(Vin.*ts.^3.*zeta.^2.*3.0-Vin.*k.*ts.^3.*zeta.^2.*3.0);
elseif (converter == 0.0)
    t0 = -(et4+et5)./(IL_ref.^4.*L.^2.*d_ref.*ts.^3.*zeta.^2.*2.7e+1+C.^2.*Vout_ref.^4.*d_ref.*ts.^3.*zeta.^2.*3.0-C.^2.*IL_ref.*R_L.*Vout_ref.^3.*ts.^3.*zeta.^2.*3.0-IL_ref.^4.*L.^2.*d_ref.*k.*ts.^3.*zeta.^2.*2.7e+1-C.^2.*Vout_ref.^4.*d_ref.*k.*ts.^3.*zeta.^2.*3.0+C.*IL_ref.^2.*L.*Vout_ref.^2.*d_ref.*ts.^3.*zeta.^2.*1.8e+1+C.^2.*IL_ref.*R_L.*Vout_ref.^3.*k.*ts.^3.*zeta.^2.*3.0-C.*IL_ref.^3.*L.*R_L.*Vout_ref.*ts.^3.*zeta.^2.*9.0+C.*IL_ref.^3.*L.*R_L.*Vout_ref.*k.*ts.^3.*zeta.^2.*9.0-C.*IL_ref.^2.*L.*Vout_ref.^2.*d_ref.*k.*ts.^3.*zeta.^2.*1.8e+1);
else
    t0 = 0.0;
end
mt2 = [t0];
if ~all(cellfun(@isscalar,{converter}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (converter == 1.0)
    t0 = (ts.^2.*zeta.^2.*-3.0+C.*L.*1.6e+1-C.*L.*k.*1.6e+1+k.*ts.^2.*zeta.^2.*3.0+C.*L.*k.*zeta.^2.*6.4e+1)./(C.*Vin.*ts.^2.*zeta.^2-C.*Vin.*k.*ts.^2.*zeta.^2);
elseif (converter == 0.0)
    t0 = -(et1+et2+et3)./((ts.^3.*zeta.^2-k.*ts.^3.*zeta.^2).*(IL_ref.^4.*L.^2.*d_ref.*9.0+C.^2.*Vout_ref.^4.*d_ref-C.^2.*IL_ref.*R_L.*Vout_ref.^3-C.*IL_ref.^3.*L.*R_L.*Vout_ref.*3.0+C.*IL_ref.^2.*L.*Vout_ref.^2.*d_ref.*6.0));
else
    t0 = 0.0;
end
mt3 = [t0];
gains_expr = [mt1;mt2;mt3];
end
